services:
  # --- INFRASTRUCTURE ---
  kafka:
    image: apache/kafka:3.7.0
    container_name: polyneige-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'polyneige-kafka-cluster-001'
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: polyneige-schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: polyneige-kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: polyneige-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    depends_on:
      kafka:
        condition: service_healthy


  # Initialisation des topics kafka (pour √©viter les erreurs dues au fait que les listeners √©coutent avant la cr√©ation des topics
  init-kafka:
    image: apache/kafka:3.7.0
    container_name: polyneige-init-kafka
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # On attend que Kafka soit pr√™t
      echo '‚è≥ Waiting for Kafka to be fully ready...'
      # On essaie de lister les topics. Si √ßa plante ou timeout, on attend 1s et on recommence.
      # Le 'timeout 5s' emp√™che la commande de rester bloqu√©e 30s si Kafka ne r√©pond pas.
      until timeout 5s /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --list; do
        echo 'zzz... Kafka not ready yet'
        sleep 2
      done

      echo 'üöÄ Kafka is ready! Creating topics...'

      echo -e 'üöÄ Creating topics...'
      # Liste de tes topics √† cr√©er
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic DLCReleased --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic SendSessionPlayTime --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic PatchReleased --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic ReviewSubmitted --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic CrashReported --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic GamePublished --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic CommentToEditor --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic CrashReportToEditor --replication-factor 1 --partitions 1



      echo -e '‚úÖ Topics created!'
      "

  # --- DATABASES ---
  db-platform:
    image: postgres:15
    container_name: polyneige-db-platform
    environment:
      POSTGRES_USER: platform_user
      POSTGRES_PASSWORD: platform_pass
      POSTGRES_DB: platform_db
    ports:
      - "5434:5432"
    volumes:
      - platform-db-data:/var/lib/postgresql/data

  db-player:
    image: postgres:15
    container_name: player-module-db-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: player-module-db
    ports:
      - "5435:5432"
    volumes:
      - player-db-data:/var/lib/postgresql/data

  db-editor:
    image: postgres:15
    container_name: polyneige-editor-db
    environment:
      POSTGRES_DB: editor_db
      POSTGRES_USER: editor_user
      POSTGRES_PASSWORD: editor_pass
    ports:
      - "5433:5432"
    volumes:
      - editor-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U editor_user -d editor_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- APPLICATIONS ---
  platform-module:
    build: 
      context: ./PlatformModule
    container_name: platform-app
    stdin_open: true   
    tty: true 
    depends_on:
      kafka:
        condition: service_healthy
      db-platform:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-platform:5432/platform_db
      SPRING_DATASOURCE_USERNAME: platform_user
      SPRING_DATASOURCE_PASSWORD: platform_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      LOGGING_LEVEL_ROOT: OFF            # Mutes all logs (Info, Debug, Warn)
      SPRING_MAIN_BANNER_MODE: "off"     # Hides the startup banner
      LOGGING_PATTERN_CONSOLE: "%msg%n"  # Ensures only raw message output
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
      LOGGING_LEVEL_ORG_HIBERNATE: "OFF"
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: "OFF"
      LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL: "OFF"

  player-module:
    build:
      context: ./PlayerModule
    container_name: player-app
    stdin_open: true   
    tty: true          
    depends_on:
      kafka:
        condition: service_healthy
      db-player:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-player:5432/player-module-db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      LOGGING_LEVEL_ROOT: OFF            # Mutes all logs (Info, Debug, Warn)
      SPRING_MAIN_BANNER_MODE: "off"     # Hides the startup banner
      LOGGING_PATTERN_CONSOLE: "%msg%n"  # Ensures only raw message output
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
      LOGGING_LEVEL_ORG_HIBERNATE: "OFF"
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: "OFF"
      LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL: "OFF"

  editor-module:
    build:
      context: ./Editor
    container_name: editor-app
    stdin_open: true
    tty: true
    depends_on:
      kafka:
        condition: service_healthy
      db-editor:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-editor:5432/editor_db
      SPRING_DATASOURCE_USERNAME: editor_user
      SPRING_DATASOURCE_PASSWORD: editor_pass
      # === SILENCING SETTINGS ===
      LOGGING_LEVEL_ROOT: OFF
      SPRING_MAIN_BANNER_MODE: "off"
      LOGGING_PATTERN_CONSOLE: "%msg%n"
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
      LOGGING_LEVEL_ORG_HIBERNATE: "OFF"
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: "OFF"
      LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL: "OFF"

volumes:
  kafka-data:
  editor-db-data:
  player-db-data:
  platform-db-data:
